name: "Test"

on:
  push:
    branches:
      - "**" # matches every branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
